---
# handlers file for kafka
- name: Boot | restarted the service using systemd
  systemd:
    name: kafka
    daemon_reload: yes
    state: restarted
    enabled: yes
  listen: "notify boot handlers"

- name: Boot | ensure the service is running
  wait_for:
    connect_timeout: 3
    delay: 15
    host: "{{ host_ip }}"
    port: "{{ item }}"
    state: started
  listen: "notify boot handlers"
  loop:
    - 9092
    #- 9093
