- name: Install Step
  vars:
    redis_dir_name: redis-7.0.11
    redis_pkg_name: redis-7.0.11.tar.gz
    redis_src_path: /usr/local/src
  block:
    - name: Install | ensure dependency packages are installed
      package: name={{ item }} update_cache=true
      loop:
        - gcc
        - g++
        - libsystemd-dev
        - make
        - pkgconf
        - unzip

    - name: Install | check the redis src path stats
      stat:
        path: "{{ redis_root_path }}"
      register: check_path_result

    - name: Install | copy the redis package to remote tmp dir
      copy:
        src: "{{ redis_pkg_name }}"
        dest: "{{ redis_src_path }}/{{ redis_pkg_name }}"
      when: not check_path_result.stat.exists

    - name: Install | unarchive redis package
      unarchive:
        src: "{{ redis_src_path }}/{{ redis_pkg_name }}"
        dest: "{{ redis_src_path }}"
        mode: 0755
        remote_src: true
      when: not check_path_result.stat.exists

    - name: Install | build redis to redis_root_path
      shell: make MALLOC=jemalloc USE_SYSTEMD=yes && make PREFIX="{{ redis_root_path }}" install
      args:
        creates: "{{ redis_root_path }}"
        chdir: "{{ redis_src_path }}/{{ redis_dir_name }}"
        executable: /bin/bash
      register: compile_result
      when: not check_path_result.stat.exists
