---
# tasks file for redis
- name: Pre-check | check if redis_root_path exists
  stat: 
    path: "{{ redis_root_path }}"
  register: redis_root_path_result

- include_tasks: install.yml
  when: not redis_root_path_result.stat.exists

- import_tasks: configure.yml

- import_tasks: cluster.yml
  when: redis_cluster_enabled == "yes"
