---
# tasks file for packages
- name: Install Base Softwares For ubuntu 20
  package: name={{ item }} state=latest update_cache=yes
  loop:
    - curl
    - dstat
    - gcc
    - make
    - mtr
    - net-tools
    - nload
    - libssl-dev
    - iftop
    - iproute2
    - sysstat 
    - telnet
    - tcpdump
    - traceroute
    - unzip
    - vim
    - wget
    - zlib1g-dev 
  # when: ansible_os_family == "Debian"
  when: ansible_distribution_file_variety  == "Debian"
