---
# tasks file for nginx
- name: Install Deps For Nginx bins
  package: name={{ item }} state=present
  loop:
    - libssl-dev
    - libpcre3-dev
    - zlib1g-dev
    - libgeoip-dev
    - libjson-c-dev

- name: Synchronize Nginx
  block:
    - name: copy nginx package
      copy: src=nginx.tar.gz  dest=/tmp/nginx.tar.gz owner=root group=root mode=644
    - name: unarchive nginx package
      unarchive: src=/tmp/nginx.tar.gz  dest=/usr/local/ group=root owner=root mode=0755 remote_src=True
    - name: delete tmp file
      file: path=/tmp/nginx.tar.gz state=absent

- name: Nginx Settings
  block:
    - name: nginx directory or bin permission
      file: path={{ item.path }} owner={{ item.user }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }} recurse={{ item.recurse }}
      loop:
        - { path: /usr/local/nginx/, mode: '0755', user: tomcat, group: tomcat, state: directory,recurse: yes }
        - { path: /usr/local/nginx/sbin/nginx, mode: '4755', user: root, group: root, state: file, recurse: no }
    - name: ldconfig path setting
      command: ldconfig /usr/local/nginx/lib/

- name: Nginx logrotate
  block:
    - name: confirm logrotate directory
      file: path=/opt/logrotate/ owner=root group=root mode='0755' state=directory
    - name: synchronize logrotate file 
      copy: src=nginx.logrotate dest=/opt/logrotate/nginx.logrotate owner=root group=root mode='0644'
    - name: add logrotate task to crontab
      cron: name='logroate nginx' minute='59' hour='23' job='/usr/sbin/logrotate -f /opt/logrotate/nginx.logrotate >> /opt/logrotate/logrotate.log 2>&1'

- name: Check and start nginx service
  block:
#    - name: checking nginx state
#      debug:
    - name: starting nginx
      command: /usr/local/nginx/sbin/nginx
