---
# tasks file for nginx
- name: Installing Dependencies for Nginx
  package: 
    name: {{ item }}
    state: present
  loop:
    - libssl-dev
    - libpcre3-dev
    - zlib1g-dev
    - libgeoip-dev
    - libjson-c-dev


- name: Installing Nginx
  block:
    - name: Copy nginx.tar.gz package and nginx.service file
      copy:
        src: {{ item.src }}
        dest: {{ item.dest }}
        owner: nginx
        group: nginx
        mode: 0644
      loop:
        - { src: nginx.tar.gz, dest: /tmp/nginx.tar.gz }
        - { src: nginx.service, dest: /etc/systemd/system/nginx.service }

    - name: Unarchive nginx package
      unarchive: 
        src: /tmp/nginx.tar.gz
        dest: /usr/local/
        group: nginx
        owner: nginx
        mode: 0755
        remote_src: true

    - name: Delete tmp file
      file: 
        path: /tmp/nginx.tar.gz
        state: absent


- name: Configure Nginx
  block:
    - name: Set nginx directory and binary file permission
      file: 
        path: {{ item.path }}
        owner: {{ item.owner }}
        group: {{ item.group }}
        mode: {{ item.mode }}
        state: {{ item.state }}
        recurse: {{ item.recurse }}
      loop:
        - { path: /usr/local/nginx/, mode: '0755', owner: nginx, group: nginx, state: directory, recurse: yes }
        - { path: /usr/local/nginx/sbin/nginx, mode: '4755', owner: nginx, group: nginx, state: file, recurse: no }

    - name: Add system library path /usr/local/nginx/lib/
      command: ldconfig /usr/local/nginx/lib/

    - name: Add nginx logrotate file 
      copy:
        src: nginx
        dest: /opt/cron/nginx
        owner: nginx
        group: nginx
        mode: 0644

    - name: Add nginx logrotate to crontab
      cron: 
        name: 'logroate nginx'
        hour: '23'
        minute: '59'
        job: '/usr/sbin/logrotate -f /opt/cron/nginx >> /opt/cron/cron.log 2>&1'


- name: Controls systemd services for nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes
