---
# tasks file for nginx
- name: Install Dependencies for Nginx
  package: name={{ item }} state=present
  loop:
    - libssl-dev
    - libpcre3-dev
    - zlib1g-dev
    - libgeoip-dev
    - libjson-c-dev

- name: Synchronize Nginx
  block:
    - name: copy nginx.tar.gz package and nginx.service file
      copy: src={{ item.src }}  dest={{ item.dest }} owner=root group=root mode=0644
      loop:
        - { src: nginx.tar.gz, dest: /tmp/nginx.tar.gz }
        - { src: nginx.service, dest: /etc/systemd/system/nginx.service }
    - name: unarchive nginx package
      unarchive: src=/tmp/nginx.tar.gz  dest=/usr/local/ group=root owner=root mode=0755 remote_src=True
    - name: delete tmp file
      file: path=/tmp/nginx.tar.gz state=absent

- name: Settings Nginx
  block:
    - name: set nginx directory and binary file permission
      file: path={{ item.path }} owner={{ item.user }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }} recurse={{ item.recurse }}
      loop:
        - { path: /usr/local/nginx/, mode: '0755', user: tomcat, group: tomcat, state: directory, recurse: yes }
        - { path: /usr/local/nginx/sbin/nginx, mode: '4755', user: root, group: root, state: file, recurse: no }
    - name: add system library path /usr/local/nginx/lib/
      command: ldconfig /usr/local/nginx/lib/

- name: Logrotate for Nginx
  block:
    - name: upload nginx logrotate file 
      copy: src=nginx  dest=/opt/cron/nginx owner=root group=root mode=644
    - name: add nginx logrotate to crontab
      cron: name='logroate nginx' minute='58' hour='23' job='/usr/sbin/logrotate -f /opt/cron/nginx >> /opt/cron/cron.log 2>&1'

- name: Controls systemd services for nginx
  block:
    - name: run daemon-reload, start, boot nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
        daemon_reload: yes
