---
# Usage:
#   ansible-playbook -i inventories/initial.hosts playbooks/initial.yml -e "hosts_var=10.0.10.12,10.0.10.13"
- hosts: "{{ hosts_var }}"
  vars:
    - ansible_port: 22 
    - ansible_user: root 
    - ansible_ssh_pass: old_root_password
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_prompt:
    - name: "new_root_password"
      prompt: "Please enter new root password"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7
  roles:
    - audit
    - disk
    - hostname
    - ntp
    - packages
    - salt-minion
    - security # iptables, ulimit
    - sysctl
    - users
    - vimrc
    - zabbix-client
    - { role: sshd, new_root_password: "{{ new_root_password }}" }
