---
# Usage:
#     ansible-playbook playbooks/nginx.yml -e "hosts_vars=10.0.10.12,10.0.10.13"
- hosts: "{{ hosts_var }}"
  remote_user: root
  become: yes
  become_method: su
  roles:
    - { role: nginx }
