---
# Usage:
#
# default inventory
#   ansible test -m ping
#   ansible-playbook playbooks/template.yml
#
# special inventory
#   ansible -i inventories/test.hosts 10.0.10.12,10.0.10.13 -m ping
#   ansible-playbook -i inventories/test.hosts playbooks/template.yml -e "hosts_var=10.0.10.12,10.0.10.13"
#
- name: Test Template Playbook
  hosts: test
  hosts: "{{ hosts_var }}"
  # become: true
  # become_user: root
  # ignore_errors: yes
  # tags: ["foo", "bar"]
  gather_facts: yes
  vars:
    - k1: v1
    - k2: v2
  tasks:
    - name: Ansible buildin ping
      #ping | ansible.builtin.ping:
      ansible.builtin.ping:
      tags:
        - debug

    - name: Debug when group_var
      debug:
        #msg: "debug test"
        var: k1
      # get host_vars or group_vars
      #when: template_host_var == "yes"
      when: template_group_var == "yes"

    - name: import tasks when syntax
      import_tasks: Debian.yml
      when: ansible_os_family == "Debian"
    - name: include tasks with loop syntax
      include_tasks: "{{item}}.yaml"
      loop:
        - i1
        - i2

    - name: system fact
      debug: msg={{ ansible_facts["default_ipv4"]["address"] }}
    - name: custom fact
      debug:
        var: ansible_local.forbidden.forbid

  # role settings
  roles:
    - role: redis
      vars:
        config: redis.conf
        port: 6379
    # custom fact data
    - role: fact 
      dir: /opt/ansible/facts.d/
      factfile: forbidden.fact
      one: aaa 
      two: bbb
  # environment settings
  environment:
    http_proxy: http://example.com:8080
    PATH: /opt/go/bin:{{ ansible_env.PATH }}

